######################################################################
# Automatically generated by qmake (3.0) Tue Aug 19 22:33:19 2014
######################################################################

TEMPLATE = app
TARGET = tree
INCLUDEPATH += .

CONFIG += c++11

# Input
HEADERS += ascii_tree.h
SOURCES += ascii_tree.cpp binary_heap.cpp
